services:
  - type: web
    name: ottawa-genai-prototype
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_VERSION
        value: 8.19.2
      - key: CI
        value: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff 