services:
  - type: web
    name: ottawa-genai-prototype
    env: node
    plan: free
    region: oregon
    buildCommand: |
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      npm install --legacy-peer-deps
      CI=false npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_VERSION
        value: 8.19.2
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff 