services:
  - type: web
    name: ottawa-genai-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      npm install --legacy-peer-deps
      CI=false npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_VERSION
        value: 8.19.2
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
      - key: REACT_APP_API_STRATEGY
        value: real
      - key: REACT_APP_API_BASE_URL
        value: https://ottawa-genai-backend.onrender.com/api/v1
      - key: REACT_APP_FALLBACK_TO_MOCK
        value: true
      - key: REACT_APP_API_TIMEOUT
        value: 10000
      - key: REACT_APP_ENABLE_DEBUG
        value: false
      - key: REACT_APP_SHOW_PROTOTYPE_BANNER
        value: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff 