services:
  - type: web
    name: ottawa-genai-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      echo "Python version: $(python --version)"
      echo "Pip version: $(pip --version)"
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: ottawa-genai-db
          property: connectionString
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Authorization

databases:
  - name: ottawa-genai-db
    plan: free
    region: oregon 