/**
 * CitationConfig - Page for citation format configuration
 *
 * Configure citation styles, display options, and thresholds.
 *
 * @module features/admin/modules/citations
 */

import { Link } from 'react-router-dom'
import {
  Quote,
  FileText,
  ArrowRight,
  Info,
  Hash,
  ListOrdered,
  Footnote,
} from 'lucide-react'

import { Button } from '@/shared/components/ui/button'
import { Badge } from '@/shared/components/ui/badge'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/shared/components/ui/card'

// Citation format options
const CITATION_FORMATS = [
  {
    id: 'inline',
    name: 'Inline Numbers',
    description: 'Citations appear as [1], [2] in text',
    example: 'The GDP grew by 5% [1]. Employment increased [2].',
    icon: Hash,
    active: true,
  },
  {
    id: 'footnote',
    name: 'Footnotes',
    description: 'Citations as superscript with footnotes at bottom',
    example: 'The GDP grew by 5%¹. Employment increased².',
    icon: Footnote,
    active: false,
  },
  {
    id: 'endnotes',
    name: 'End Sources List',
    description: 'All sources listed at the end of response',
    example: 'Sources:\n1. Report Q1 2024 (Page 5)\n2. Analysis (Page 12)',
    icon: ListOrdered,
    active: false,
  },
]

// Display fields that can be shown
const DISPLAY_FIELDS = [
  { id: 'title', name: 'Document Title', enabled: true },
  { id: 'page', name: 'Page Number', enabled: true },
  { id: 'source', name: 'Source Name', enabled: true },
  { id: 'score', name: 'Relevance Score', enabled: false },
  { id: 'date', name: 'Document Date', enabled: false },
]

export default function CitationConfig() {
  return (
    <div className="p-6 space-y-6">
      {/* Page header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Citation Config</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Configure how citations appear in RAG responses
        </p>
      </div>

      {/* Info card */}
      <Card className="border-emerald-200 bg-emerald-50/50 dark:border-emerald-900 dark:bg-emerald-950/20">
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <Info className="h-4 w-4 text-emerald-500" />
            Citation Format
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          <p>
            Citations are generated by the LLM based on the <strong>citation_format</strong> prompt.
            The current format uses inline numbered references [1], [2] that link to source documents.
          </p>
          <Link to="/admin/prompt-studio">
            <Button variant="link" className="px-0 mt-2">
              <FileText className="h-4 w-4 mr-1" />
              Edit Citation Format Prompt
              <ArrowRight className="h-4 w-4 ml-1" />
            </Button>
          </Link>
        </CardContent>
      </Card>

      {/* Citation Formats */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Quote className="h-5 w-5" />
            Citation Styles
          </CardTitle>
          <CardDescription>
            Available citation format options
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-3">
            {CITATION_FORMATS.map((format) => {
              const Icon = format.icon
              return (
                <div
                  key={format.id}
                  className={`rounded-lg border p-4 space-y-3 ${
                    format.active ? 'border-primary bg-primary/5' : ''
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Icon className="h-4 w-4 text-muted-foreground" />
                      <h3 className="font-medium">{format.name}</h3>
                    </div>
                    {format.active && (
                      <Badge variant="default" className="text-xs">
                        Active
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground">{format.description}</p>
                  <div className="bg-muted p-2 rounded text-xs font-mono whitespace-pre-wrap">
                    {format.example}
                  </div>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Display Fields */}
      <Card>
        <CardHeader>
          <CardTitle>Source Display Fields</CardTitle>
          <CardDescription>
            Information shown when a citation is expanded
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {DISPLAY_FIELDS.map((field) => (
              <div
                key={field.id}
                className="flex items-center justify-between py-2 border-b last:border-0"
              >
                <span className="text-sm">{field.name}</span>
                <Badge variant={field.enabled ? 'default' : 'secondary'}>
                  {field.enabled ? 'Shown' : 'Hidden'}
                </Badge>
              </div>
            ))}
          </div>
          <p className="text-xs text-muted-foreground mt-4">
            Note: Field visibility is controlled by the citation format prompt.
            Edit the prompt to customize which fields appear.
          </p>
        </CardContent>
      </Card>

      {/* Thresholds */}
      <Card>
        <CardHeader>
          <CardTitle>Citation Thresholds</CardTitle>
          <CardDescription>
            Settings that control citation behavior
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="p-4 border rounded-lg">
              <div className="text-sm font-medium">Minimum Relevance Score</div>
              <div className="text-2xl font-bold mt-1">0.5</div>
              <p className="text-xs text-muted-foreground mt-1">
                Sources below this score are not cited
              </p>
            </div>
            <div className="p-4 border rounded-lg">
              <div className="text-sm font-medium">Maximum Citations</div>
              <div className="text-2xl font-bold mt-1">5</div>
              <p className="text-xs text-muted-foreground mt-1">
                Maximum sources shown per response
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
